name: flugo_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <=3.0.1"

dependencies:
  dio: ^5.0.0
  file_picker: ^5.2.10
  firebase_core: ^2.7.1
  get_it: ^7.2.0
  auto_route: ^6.2.0
  auto_route_generator: ^6.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  flutter_feather_icons: ^2.0.0+1
  flutter_spinkit: ^5.1.0
  internet_connection_checker: ^1.0.0+1
  google_nav_bar: ^5.0.6
  logger: ^1.1.0
  shimmer: ^2.0.0
  simple_gradient_text: ^1.2.4
  dartz: ^0.10.1
  feather_icons: ^1.2.0
  equatable: ^2.0.5
  salomon_bottom_bar: ^3.3.2
  bot_toast: ^4.0.3
  retrofit: ^4.0.1
  shared_preferences: ^2.1.1
  flutter_animate: ^4.1.1+1
  custom_pop_up_menu: ^1.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  retrofit_generator: ">=5.0.0 <6.0.0"
  json_serializable: ^6.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/image_assets/
    - assets/gif_assets/
    - assets/avatar_frames_assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Laila
      fonts:
        - asset: fonts/Laila-Regular.ttf
        - asset: fonts/Laila-Bold.ttf
          weight: 700
    - family: Josefin
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
        - asset: fonts/JosefinSans-Bold.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
